services:
  postgres:
    image: postgres:16-alpine
    container_name: flowspace-postgres
    environment:
      POSTGRES_USER: flowspace
      POSTGRES_PASSWORD: flowspace
      POSTGRES_DB: flowspace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7-jammy
    container_name: flowspace-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: flowspace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: