"""add must_change_password to users

Revision ID: 3b4613a9dc31
Revises: 6daaf1a6d448
Create Date: 2026-05-21 00:00:13.420915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4613a9dc31'
down_revision: Union[str, Sequence[str], None] = '6daaf1a6d448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
